#%RAML 1.0 NamedExample

Value:
  eid: E1007
  userName: Rachel Green
  emailId:  Rachie123@xyz.com
  contactNo: 09999555555
  dateFrom: 2021-11-20
  toDate: 2021-11-25
  query: Can i rent a car for month with discount
