#%RAML 1.0 NamedExample

Value:
  eid: E1001
  userName: Charlie Harper
  emailId:   charlie123@xyz.com 
  contactNo: 08937652622
  dateFrom: 2000-11-20
  toDate: 2000-11-25
  query: I am unable to book a car